In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.0.1+cu118


##Introduction

In [4]:
scalar = torch.tensor(7)
print(scalar)
scalar.ndim

tensor(7)


0

In [6]:
vector = torch.tensor([7,7])
print(f"vector dim : {vector.ndim}")
print(f"vector shape : {vector.shape}")

vector dim : 1
vector shape : torch.Size([2])


In [12]:
Matrix = torch.tensor([[1,2,3],[3,4,5]])
print(f"matrix dim = {Matrix.ndim}")
print(f"matrix shape = {Matrix.shape}")

matrix dim = 2
matrix shape = torch.Size([2, 3])


In [13]:
Matrix[0]

tensor([1, 2, 3])

In [14]:
#Tensor

tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


In [20]:
tensor[0][1][2]
#zero is first 3 dimenesional matrix
#next is which row it is in
# next is which column it is in

tensor(6)

##Random tensors

Random tensors are important because the way many neural networks learn is that they can start with tensors full of random numbers and then adjust those random numbers to better represent the data

Docs :- https://pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6180, 0.0352, 0.7680, 0.9282],
        [0.4580, 0.3264, 0.9853, 0.4554],
        [0.8140, 0.0107, 0.7640, 0.5412]])

In [24]:
# Create a random tensor with similar shape to an mage tensor
random_image_tensor = torch.rand(size = (224,224,3)) # height , width , colour channels(R,Y,B)
random_image_tensor.shape

torch.Size([224, 224, 3])

##Zeros and ones

In [25]:
zeros = torch.zeros(size = (3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
ones = torch.ones(size = (3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

##Creating a range of tensors

In [28]:
torch.range(0,10)

<ipython-input-28-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
one_to_ten = torch.arange(1,10)

In [31]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor data types

**Note** Tensor datatypes is the one of the 3 big issues in the pytorch

1. Tensors not right datatype
2. Tensors not in right shape
3. Tensors not in right device

docs - https://pytorch.org/docs/stable/tensors.html

In [36]:
float_16_tensor = torch.tensor([3.0,6.0,9.0] , dtype = torch.float16, device = None , requires_grad = False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

##Manipulating Tensors

Tensor operations include:

1. Addition
2. Subraction
3. Multiplication(element - wise)
4. Divsion
5. Matrix multiplication

In [37]:
tensor = torch.tensor([1,2,3])

In [38]:
print(tensor + 10)
print(tensor - 1)
print( tensor * 2)
print(tensor / 2)

tensor([11, 12, 13])
tensor([0, 1, 2])
tensor([2, 4, 6])
tensor([0.5000, 1.0000, 1.5000])


In [39]:
#inbuilt fns
torch.mul(tensor,2)

tensor([2, 4, 6])

In [40]:
torch.matmul(tensor,tensor)
#dot product

tensor(14)

In [41]:
%%time
value = 0
for i in range(len(tensor)) :
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.63 ms, sys: 1.02 ms, total: 2.64 ms
Wall time: 2.46 ms


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.21 ms, sys: 10 µs, total: 1.22 ms
Wall time: 1.15 ms


tensor(14)

In [45]:
tensor_a = torch.tensor([[1,2],[3,4]])
tensor_b = tensor_a.T
tensor_b

tensor([[1, 3],
        [2, 4]])

##Finding max , mean , sum

In [46]:
x = torch.arange(0,100,10)

In [47]:
torch.max(x)

tensor(90)

In [51]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [52]:
torch.sum(x)

tensor(450)

In [53]:
torch.argmin(x) , torch.argmax(x)

(tensor(0), tensor(9))

# Reshaping , stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combining multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor  
* Permute - return a view of the input with dimensions permuted(swapped) in a certian way

In [54]:
y = torch.arange(1.,10.)

In [65]:
y_reshaped = y.reshape(1,9)
y_reshaped

tensor([[-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.]])

In [59]:
z = y.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [60]:
# Changing z changes the y because they share the same memory lets see
z[: , 0] = -1
z,y

(tensor([[-1.,  2.,  3.],
         [-1.,  5.,  6.],
         [-1.,  8.,  9.]]),
 tensor([-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.]))

In [64]:
y_stacked = torch.stack([y,y] , dim = 0)
y_stacked

tensor([[-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.],
        [-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.]])

In [66]:
print(f"y_reshaped : {y_reshaped}")
print(f"shape : {y_reshaped.shape}")

y_squeezed = y_reshaped.squeeze()
print(f"y_squeezed : {y_squeezed}")
print(f"shape : {y_squeezed.shape}")

y_reshaped : tensor([[-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.]])
shape : torch.Size([1, 9])
y_squeezed : tensor([-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.])
shape : torch.Size([9])


In [67]:
y_unsqueezed = y_squeezed.unsqueeze(dim = 0)
y_unsqueezed

tensor([[-1.,  2.,  3., -1.,  5.,  6., -1.,  8.,  9.]])

In [68]:
y_unsqueezed1 = y_squeezed.unsqueeze(dim = 1)
y_unsqueezed1

tensor([[-1.],
        [ 2.],
        [ 3.],
        [-1.],
        [ 5.],
        [ 6.],
        [-1.],
        [ 8.],
        [ 9.]])

In [71]:
x = torch.randn(2, 3, 5)
print(x.size())
torch.permute(x, (2, 0, 1)).size()
torch.Size([5, 2, 3])

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

##Reproducibility(trying to tale random of random)

To reduce the randomness in neural networks and pytorch comes the concept of a random seed

Essentially what the random seed does is "falvour" the randomness


In [73]:
A = torch.rand(3,3)
B = torch.rand(3,3)

A == B

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [75]:
# So lets make it some reproducible random tensors

Random_Seed = 40
torch.manual_seed(Random_Seed)

C = torch.rand(3,3)
torch.manual_seed(Random_Seed)
D = torch.rand(3,3)

print(C)
print(D)
print(C == D)

tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878],
        [0.5501, 0.1318, 0.2897]])
tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878],
        [0.5501, 0.1318, 0.2897]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


#GPU

The reasons why we want our tensors/models on gpu is because using a gpu results in faster computations

In [76]:
torch.cuda.is_available()
#Because now my run type is cpu

False

In [78]:
torch.cuda.device_count()

0

In [80]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [83]:
tensor_on_device = tensor.to(device)
tensor_on_device.device

device(type='cpu')